### PR TITLE
Add macos-latest, windows-latest, ubuntu-20.04 to build

### LINKED ISSUE #33: Move linting script into `test.yml`
## Description
Currently, the linting/type checking/formatting checks performed by CI are housed in a separate script, `lint_python.sh`, which is called by the `test.yml` test script. While this keeps the test script clean, it makes it difficult to work out which check is causing a failure.

We should move the checks from `lint_python.sh` into `test.yml`, so we can easily see what's causing failures

## Type of Test
- [ ] **Unit test** (e.g. checking a loop, method, or function is working as intended)
- [ ] **Integration test** (e.g. checking if a certain group or set of functionality is working as intended)
- [ ] **Regression test** (e.g. checking if by adding or removing a module of code allows other systems to continue to function as intended)
- [ ] **Stress test** (e.g. checking to see how well a system performs under various situations, including heavy usage)
- [ ] **Performance test** (e.g. checking to see how efficient a system is as performing the intended task)
- [X] Other... Change to code linting test script

## Expected Behavior
In the linting stage of the CI logs, each command (e.g. flake8, black, mypy) should be a separate, collapsible command

### LINKED ISSUE #43: Add Windows and MacOS tests
## Description
Add test builds on Windows and MacOS. PyVertical involves a code compilation step (PSI) which varies system to system, so it is important we test all common OSs to catch bugs.

To save time, only test Python 3.7 on each new OS

## Type of Test
- [X] **Unit test** (e.g. checking a loop, method, or function is working as intended)
- [ ] **Integration test** (e.g. checking if a certain group or set of functionality is working as intended)
- [ ] **Regression test** (e.g. checking if by adding or removing a module of code allows other systems to continue to function as intended)
- [ ] **Stress test** (e.g. checking to see how well a system performs under various situations, including heavy usage)
- [ ] **Performance test** (e.g. checking to see how efficient a system is as performing the intended task)
- [ ] Other...

## Expected Behavior
Opening a PR should run tests on:
- Ubuntu 18.04
    - Python 3.6, 3.7, 3.8 (current behaviour)
- Windows (latest version available on github CI)
    - Python 3.7
- MacOS (latest version available on github CI)
    - Python 3.7

### PR DESCRIPTION
**Pull request by TTitcombe**
## Description
Adds builds in macos, ubuntu 20.04 to build scripts.
These builds only test python 3.7 and do not run linting checks on the code

Also moves the contents of `lint_python.sh` to `test.yml`. This makes it easier to see which linting check failed

Fixes partially #43
Fixes #33 

## Checklist
- [X] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [X] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [X] My changes are covered by tests

### CODE REVIEW

**Comment by TTitcombe** [comment]
@pavlos-p you're on windows, right? Can you have a look at why the windows build can't install torch?

**Comment by pavlos-p** [comment]
Created an [Issue on the PSI repo](https://github.com/OpenMined/PSI/issues/77) for the Windows build fail.

**Comment by TTitcombe** [comment]
Windows build fails on known issue. See https://github.com/OpenMined/PSI/issues/77

**Comment by TTitcombe** [comment]
Removing the failing windows build and merging

**Pull request merged**
